name: GitHub Releases Push
on:
  release:
    types:
      - created
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build image
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: ${{ secrets.GHCR_USERNAME }}/ofelia
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Tag image
      if: github.event_name == 'release'
      uses: mr-smithers-excellent/docker-build-push@v2
      with:
        image: ${{ secrets.GHCR_USERNAME }}/ofelia
        registry: ghcr.io
        tag: latest
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}